targets:
  $default:
    sources:
      exclude:
        - lib/src/_inactive/**
    builders:
      freezed:
        options:
          check: false
          map_factory: true
          equal: true
          to_string: true
      freezed|freezed:
        enabled: true
        options:
          line_length: 80
